# Generated by Django 4.2.2 on 2023-06-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='previous_posts', max_length=255, unique=True),
        ),
    ]
